upd-ci

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -9,6 +9,10 @@ on:
 permissions:
   contents: read
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   tests:
     name: "Python ${{ matrix.python-version }}"
@@ -16,7 +20,7 @@ jobs:
 
     strategy:
       matrix:
-        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
+        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]
 
     steps:
       - uses: actions/checkout@v6
@@ -24,6 +28,7 @@ jobs:
         uses: astral-sh/setup-uv@v7
         with:
           python-version: ${{ matrix.python-version }}
+          enable-cache: true
 
       - name: "Install dependencies"
         run: uv sync --locked --no-default-groups --no-install-project --group dev --group test
@@ -36,3 +41,17 @@ jobs:
 
       - name: "Enforce coverage"
         run: uv run coverage report --show-missing --skip-covered --fail-under=100
+
+  check-tests:
+    name: "Tests successful"
+    needs: [tests]
+    runs-on: "ubuntu-latest"
+    if: always()
+
+    steps:
+      - name: "Check results"
+        run: |
+          if [ "${{ needs.tests.result }}" != "success" ]; then
+            echo "Tests failed"
+            exit 1
+          fi
